# Generated by Django 4.0.3 on 2022-03-13 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GenarateCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('outlet', models.CharField(choices=[('Room Service', 'Room Service'), ('Thoe', 'Thoe Randal'), ('Arch Bar', 'Arch Bar'), ('Wellington Lounge', 'Wellington Lounge'), ('Number One', 'Number One'), ('BQT', 'BQT')], max_length=200)),
            ],
        ),
    ]
