# Generated by Django 4.0.3 on 2022-03-30 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Qrcode', '0002_alter_genaratecode_outlet'),
    ]

    operations = [
        migrations.AddField(
            model_name='genaratecode',
            name='date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
