# Generated by Django 4.0.3 on 2022-05-22 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Qrcode', '0005_remove_qrcodesfordishes_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='qrcodesfordishes',
            name='date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='qrcodesfordishes',
            name='outlet',
            field=models.CharField(default='q', max_length=200),
        ),
        migrations.AlterField(
            model_name='qrcodesfordishes',
            name='img',
            field=models.CharField(default='q', max_length=200000),
        ),
    ]
