# Generated by Django 4.0.3 on 2022-05-28 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Qrcode', '0011_alter_qrcodesfordishes_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qrcodesfordishes',
            name='img',
            field=models.TextField(max_length=200000),
        ),
    ]
