# Generated by Django 4.0.3 on 2022-03-26 18:19

import Qrcode.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Qrcode', '0002_alter_genaratecode_outlet'),
    ]

    operations = [
        migrations.CreateModel(
            name='Beverage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('brand', models.CharField(max_length=400)),
                ('description', models.TextField(max_length=4000)),
                ('alcohol_type', models.CharField(choices=[('Soft', 'Soft'), ('Coffee', 'Coffee'), ('Tea', 'Tea'), ('Juice', 'Juice'), ('Beer', 'Beer'), ('Wine', 'Wine'), ('Sparkling Wine', 'Sparkling Wine'), ('Spirit', 'Spirit'), ('Shot', 'Shot')], max_length=200)),
                ('alergens', models.CharField(max_length=1000)),
            ],
            options={
                'ordering': ('title',),
            },
        ),
        migrations.CreateModel(
            name='Dish_Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('outlet', models.CharField(choices=[('Room Service', 'Room Service'), ('Thoe', 'Thoe Randal'), ('Arch Bar', 'Arch Bar'), ('Wellington Lounge', 'Wellington Lounge'), ('Number One', 'Number One'), ('BQT', 'BQT'), ('Amenities', 'Amenities')], default='Recipe', max_length=200)),
                ('type_dish', models.CharField(choices=[('Starter', 'Starter'), ('Main', 'Main'), ('Dessert', 'Dessert'), ('Amenities', 'Amenities')], default='Recipe', max_length=200)),
                ('recipe', models.TextField(max_length=4000)),
                ('method', models.TextField(max_length=6000)),
                ('archived', models.BooleanField(null=True)),
                ('shared', models.BooleanField(null=True)),
            ],
            options={
                'ordering': ('title',),
            },
        ),
        migrations.CreateModel(
            name='SharedRecipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('type_dish', models.CharField(choices=[('Starter', 'Starter'), ('Main', 'Main'), ('Dessert', 'Dessert'), ('Amenities', 'Amenities')], max_length=200)),
                ('recipe', models.TextField(max_length=4000)),
                ('method', models.TextField(max_length=6000)),
                ('archived', models.BooleanField(default=False)),
                ('dish_title', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='info.dish_recipe')),
            ],
            options={
                'ordering': ('title',),
            },
        ),
        migrations.CreateModel(
            name='Pairing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bev_title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Pairing_Drink', to='info.beverage')),
                ('dish_title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Pairing_Dish', to='info.dish_recipe')),
            ],
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('dessert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Dess', to='info.dish_recipe')),
                ('drink', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Drink', to='info.beverage')),
                ('main', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Main', to='info.dish_recipe')),
                ('starters', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Start', to='info.dish_recipe')),
            ],
        ),
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('image', models.FileField(upload_to='media')),
                ('description', models.TextField(max_length=3000)),
                ('qr_code', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='qr_code', to='Qrcode.genaratecode', verbose_name=Qrcode.models.GenarateCode)),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='info.dish_recipe')),
                ('sub_recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='info.sharedrecipe')),
            ],
        ),
    ]
