# Generated by Django 4.0.3 on 2022-03-26 18:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='sub_recipe',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='info.sharedrecipe'),
        ),
    ]
