# Generated by Django 4.0.3 on 2022-03-20 18:41

import Qrcode.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Qrcode', '__first__'),
        ('info', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='qr_code',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, related_name='qr_code', to='Qrcode.genaratecode', verbose_name=Qrcode.models.GenarateCode),
        ),
    ]
