# Generated by Django 4.0.3 on 2022-03-26 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0002_alter_dish_sub_recipe'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dish',
            name='qr_code',
        ),
        migrations.RemoveField(
            model_name='dish',
            name='sub_recipe',
        ),
    ]
