# Generated by Django 4.0.3 on 2022-03-15 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0002_dish'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Dish',
        ),
    ]
