# Generated by Django 4.0.3 on 2022-03-15 19:19

from django.db import migrations, models
import django.db.models.deletion
import qrcode.models


class Migration(migrations.Migration):

    dependencies = [
        ('qrcode', '0001_initial'),
        ('info', '0003_delete_dish'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(max_length=3000)),
                ('Qrcode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                 related_name='qrcode', to='qrcode.genaratecode', verbose_name=qrcode.models.GenarateCode)),
                ('recipe', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE, to='info.dish_recipe')),
                ('sub_recipe', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE, to='info.sharedrecipe')),
            ],
        ),
    ]
