# Generated by Django 4.0.3 on 2022-03-25 05:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0004_alter_sharedrecipe_dish_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish_recipe',
            name='sub_recipe',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='info.sharedrecipe'),
        ),
        migrations.AlterField(
            model_name='sharedrecipe',
            name='dish_title',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='info.dish_recipe'),
        ),
    ]
