# Generated by Django 4.0.3 on 2022-03-30 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0004_dish_qr_code_dish_sub_recipe_alter_dish_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='beverage',
            name='date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='dish',
            name='date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='dish_recipe',
            name='date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='menu',
            name='date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='sharedrecipe',
            name='date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
