# Generated by Django 4.0.3 on 2022-03-26 06:44

import Qrcode.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Qrcode', '0002_alter_genaratecode_outlet'),
        ('info', '0006_remove_dish_recipe_sub_recipe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='qr_code',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='qr_code', to='Qrcode.genaratecode', verbose_name=Qrcode.models.GenarateCode),
        ),
    ]
