# Generated by Django 4.0.3 on 2022-04-10 10:21

import Qrcode.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Qrcode', '0003_genaratecode_date'),
        ('info', '0007_dish_recipe_dish_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='qr_code',
            field=models.ForeignKey(blank=True, default=0, on_delete=django.db.models.deletion.CASCADE, related_name='qr_code', to='Qrcode.genaratecode', verbose_name=Qrcode.models.GenarateCode),
        ),
        migrations.AlterField(
            model_name='dish',
            name='sub_recipe',
            field=models.ForeignKey(blank=True, default=0, on_delete=django.db.models.deletion.CASCADE, to='info.sharedrecipe'),
        ),
    ]
