# Generated by Django 4.0.3 on 2022-03-26 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0007_alter_dish_qr_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish_recipe',
            name='archived',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='dish_recipe',
            name='shared',
            field=models.BooleanField(null=True),
        ),
    ]
