# Generated by Django 4.0.3 on 2022-04-10 11:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0008_alter_dish_qr_code_alter_dish_sub_recipe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='drink',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='Drink', to='info.beverage'),
        ),
    ]
