# Generated by Django 4.0.3 on 2022-04-10 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0009_alter_menu_drink'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calory',
            name='unit',
            field=models.CharField(choices=[('g', 'g'), ('kg', 'kg'), ('ml', 'ml'), ('lit', 'lit')], max_length=200),
        ),
    ]
