# Generated by Django 4.0.3 on 2022-04-17 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0010_alter_calory_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish_recipe',
            name='portions',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='sharedrecipe',
            name='portions',
            field=models.IntegerField(default=1),
        ),
    ]
