# Generated by Django 4.0.3 on 2022-04-17 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0013_remove_dish_choose_recipe_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sharedrecipe',
            name='type_dish',
            field=models.CharField(choices=[('Starter', 'Starter'), ('Main', 'Main'), ('Dessert', 'Dessert'), ('Amenities', 'Amenities')], default='Recipe', max_length=200),
        ),
    ]
