# Generated by Django 4.0.3 on 2022-04-17 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0014_alter_sharedrecipe_type_dish'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wights',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('amout', models.IntegerField()),
                ('wight', models.FloatField()),
            ],
        ),
    ]
