# Generated by Django 4.0.3 on 2022-04-17 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0015_wights'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wights',
            name='amout',
            field=models.IntegerField(default=1),
        ),
    ]
