# Generated by Django 4.0.3 on 2022-04-18 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0016_alter_wights_amout'),
    ]

    operations = [
        migrations.CreateModel(
            name='Allergents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('allergent', models.CharField(choices=[('Celery', 'Celery'), ('Gluten', 'Gluten'), ('Crustaceans', 'Crustaceans'), ('Eggs', 'Eggs'), ('Fish', 'Fish'), ('Lupin', 'Lupin'), ('Milk', 'Milk'), ('Molluscs', 'Molluscs'), ('Mustard', 'Mustard'), ('Nuts', 'Nuts'), ('Peanuts', 'Peanuts'), ('Sesame seeds', 'Sesame seeds'), ('Soya', 'Soya'), ('Sulphur dioxide', 'Sulphur dioxide')], max_length=200)),
                ('description', models.CharField(max_length=1000)),
                ('date', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
    ]
